### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by flanigangj**
Minor edits created during a read through to compare with internal NCI documentation.

### CODE REVIEW

**Review by dirkpetersen — CHANGES_REQUESTED** [review]
Thank you for you input @flanigangj those are great edits,  the only thing I would want to check on: 

installed by the `Project Admin`, this role can be filled by the IT department `or coordinating researcher` of the organization that is responsible for installing the central infrastructure

The coordinating researcher can be misleading as the role and responsibilities should be clearly separated. It does not have to be the IT department though, how about :

`this role can be filled by the IT department or another neutral entity, that is not directly associated with the team conducting federated learning in the organization that is responsible....`

**Comment by flanigangj** [comment]
Hey @dirkpetersen, I completely agree with that change. I was struggling with how to word that statement, but I thought it important for researchers to know that they could do it themselves without involving and IT department. Thank you!!

**Comment by flanigangj** [comment]
Clicked the wrong button

**Comment by dirkpetersen** [comment]
@flanigangj, i checked back with stakeholders an the consensus was that IT professionals need to fill the project admin role: An individual with this role is responsible for setting up the project and approving requesting sites and users.  Should be a senior IT/IPS professional from one of the collaborating sites. Individuals with this role are in charge of server security and by default have unrestricted access to the NVFlare system.  This is somewhat in line with dbGap request where you need to designate an IT director of the organization

**Pull request merged**
